spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true
  username: cam2
  password: cam2
  driver-class-name: org.postgresql.Driver
camunda.bpm:
  admin-user:
    id: cam2
    password: cam2
    firstName: Tac
  filter:
    create: All tasks
server.port: 8082
server:
  servlet:
    context-path: /cam2
camunda:
  bpm:
    database:
      schema-name: cam2
      table-prefix: cam2.